### ISSUE TITLE
Compare error handling in Swift and Go

### ISSUE THREAD

**Issue by mathie** [mathie/mathie.github.io#6]
I have this nagging feeling that Swift does error handling the wrong way around. So far, I've found that the optional support (which is awesome because it makes error handling explicit, and that's better than allowing developers to ignore errors!) seems to encourage the following:

``` swift
if let foo = fetchFoo() {
    if let bar = foo.bar() {
        // Do something with bar

        return bar
    } else {
        println("An error occurred with foo.bar()")
        return nil
    }
} else {
    println("An error occurred with fetchFoo()")
    return nil
}
```

I wind up with deeply nested if statements trying to get to the code I want to do. Of course, deeper nesting can be reduced by factoring code out into separate functions, but still.

Instead with Go (at least in my rudimentary understanding of it), you wind up doing:

``` go
foo, err := fetchFoo()
if err != nil {
  logger.logF("Something went wrong with fetchFoo(): %@", err)
  return nil, err
}
bar, err := foo.bar()
if err != nil {
  logger.logF("Something went wrong with foo.bar(): %@", err)
  return nil, err
}
// Do something with bar
return bar, nil
```

The code is just as verbose in both cases, really. In the Swift example, the happy path is perhaps a bit clearer, because it's not cluttered with error handling code. But on the other hand, the happy case winds up being nested in deeper and deeper `if` statements. The Go version retains more information about the error (without resorting to passing in an address to an `NSError` object), and it stays nicely lined up with the left margin.

Am I doing it wrong in Swift?

**Comment by mathie** [comment]
FIXME: I just made the code up off the top of my head. I've no idea if it's valid Swift code, or valid Go!

**Comment by srbaker** [comment]
I forget the details, because it's been a few months, but I'm pretty sure this is where you deal with optionals, and ? in Swift. But that's as far as my brain will go right now.

**Comment by mathie** [comment]
Yeah, the `if let` syntax is a neat way of unwrapping optionals. You make a good point, though. You could blindly ignore errors with:

``` swift
let foo = fetchFoo()!
let bar = foo.bar()!
// Do something with bar
return bar
```

which is much more compact, if you know that neither will be nil in reality. Thinking about it the other way around, I could do:

``` swift
let optionalFoo = fetchFoo()
if optionalFoo == nil {
    println(“It all went wrong with fetchFoo()”)
    return nil
}
let foo = optionalFoo!
let optionalBar = foo.bar()
if optionalBar == nil {
    println(“It all went wrong with bar()”)
    return nil
}
let bar = optionalBar!
// Do something with bar
return bar
```

but that feels even uglier…

**Comment by mathie** [comment]
Hmm, do triple backtick blocks not work in comments?
